// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module rooch_test_proj1::rooch_test_proj1_init {
    use moveos_std::storage_context::StorageContext;
    use rooch_test_proj1::article;
    use rooch_test_proj1::order;
    use rooch_test_proj1::product;
    use rooch_test_proj1::tag;

    public entry fun initialize(storage_ctx: &mut StorageContext, account: &signer) {
        article::initialize(storage_ctx, account);
        tag::initialize(storage_ctx, account);
        order::initialize(storage_ctx, account);
        product::initialize(storage_ctx, account);
    }

}
